import type { Config } from "@react-router/dev/config"
import { readFileSync } from "fs"
import { join } from "path"

type ContentIndex = {
  generatedAt: string
  posts: { slug: string; category: string; tags: string[] }[]
  docs: { slug: string }[]
}

export default {
  // SPA mode — no runtime server needed
  ssr: false,
  // Pre-render all routes to static HTML
  async prerender() {
    const paths: string[] = ["/", "/about", "/search"]

    try {
      // Read the content index generated by scripts/build.mjs
      const indexPath = join(process.cwd(), "public", "content-index.json")
      const raw = readFileSync(indexPath, "utf-8")
      const index: ContentIndex = JSON.parse(raw)

      // Blog routes
      for (const post of index.posts) {
        paths.push(`/blog/${post.slug}`)
      }
      // Blog category & tag index pages
      const categories = new Set(index.posts.map((p) => p.category))
      for (const cat of categories) {
        paths.push(`/blog/category/${cat}`)
      }
      const tags = new Set(index.posts.flatMap((p) => p.tags || []))
      for (const tag of tags) {
        paths.push(`/blog/tag/${tag}`)
      }

      // Docs routes
      paths.push("/docs")
      for (const doc of index.docs) {
        paths.push(`/docs/${doc.slug}`)
      }
    } catch {
      // Fallback: just prerender static routes
      paths.push("/blog", "/blog/category", "/blog/tags")
    }

    return paths
  },
} satisfies Config
