// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/category": {
    params: {};
  };
  "/blog/category/:name": {
    params: {
      "name": string;
    };
  };
  "/blog/tags": {
    params: {};
  };
  "/blog/tag/:tag": {
    params: {
      "tag": string;
    };
  };
  "/blog/:slug/*": {
    params: {
      "slug": string;
      "*": string;
    };
  };
  "/docs": {
    params: {};
  };
  "/docs/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/search" | "/blog" | "/blog/category" | "/blog/category/:name" | "/blog/tags" | "/blog/tag/:tag" | "/blog/:slug/*" | "/docs" | "/docs/*";
  };
  "../src/routes/_index.tsx": {
    id: "../src/routes/_index";
    page: "/";
  };
  "../src/routes/about.tsx": {
    id: "../src/routes/about";
    page: "/about";
  };
  "../src/routes/search._index.tsx": {
    id: "../src/routes/search._index";
    page: "/search";
  };
  "../src/layouts/BlogLayout.tsx": {
    id: "../src/layouts/BlogLayout";
    page: "/blog" | "/blog/category" | "/blog/category/:name" | "/blog/tags" | "/blog/tag/:tag" | "/blog/:slug/*";
  };
  "../src/routes/blog._index.tsx": {
    id: "../src/routes/blog._index";
    page: "/blog";
  };
  "../src/routes/blog.category._index.tsx": {
    id: "../src/routes/blog.category._index";
    page: "/blog/category";
  };
  "../src/routes/blog.category.$name.tsx": {
    id: "../src/routes/blog.category.$name";
    page: "/blog/category/:name";
  };
  "../src/routes/blog.tags._index.tsx": {
    id: "../src/routes/blog.tags._index";
    page: "/blog/tags";
  };
  "../src/routes/blog.tag.$tag.tsx": {
    id: "../src/routes/blog.tag.$tag";
    page: "/blog/tag/:tag";
  };
  "../src/routes/blog.$slug.tsx": {
    id: "../src/routes/blog.$slug";
    page: "/blog/:slug/*";
  };
  "../src/layouts/DocsLayout.tsx": {
    id: "../src/layouts/DocsLayout";
    page: "/docs" | "/docs/*";
  };
  "../src/routes/docs._index.tsx": {
    id: "../src/routes/docs._index";
    page: "/docs";
  };
  "../src/routes/docs.$section.$slug.tsx": {
    id: "../src/routes/docs.$section.$slug";
    page: "/docs/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "../src/routes/_index": unknown;
  "../src/routes/about": unknown;
  "../src/routes/search._index": unknown;
  "../src/layouts/BlogLayout": unknown;
  "../src/routes/blog._index": unknown;
  "../src/routes/blog.category._index": unknown;
  "../src/routes/blog.category.$name": unknown;
  "../src/routes/blog.tags._index": unknown;
  "../src/routes/blog.tag.$tag": unknown;
  "../src/routes/blog.$slug": unknown;
  "../src/layouts/DocsLayout": unknown;
  "../src/routes/docs._index": unknown;
  "../src/routes/docs.$section.$slug": unknown;
};